### ISSUE TITLE
Add your name to the contributors list

### ISSUE THREAD

**Issue by monsij** [monsij/HelloWorld_Hacktober19#24]
Add as per the following template in `CONTRIBUTORS.md`

#### Name: XYZ-ABC
 - Place: Lorem Ipsum
 - Bio: Something about you
 - GitHub: [NAME](https://github.com/monsij)

Feel free to address other issue as well a.k.a #2

**Comment by iamrishav** [comment]
i want to add my name

**Comment by monsij** [comment]
> i want to add my name

Sure. Fork the repository and get started

**Comment by Exodus5656** [comment]
Name: Joshaua Smart
Place: Texas
Bio: New to GitHub learning python
GitHub: Exodus5656

Added hello_world in python3

**Comment by monsij** [comment]
> Name: Joshaua Smart
> Place: Texas
> Bio: New to GitHub learning python
> GitHub: Exodus5656
> 
> Added hello_world in python3

make a PR @Exodus5656
